# Configurações do banco de dados PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=reco_df
quarkus.datasource.password=reco_df_pass
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5435/reco_df_db

# Configurações do Hibernate ORM com Panache
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configurações do SmallRye OpenAPI (Swagger UI)
quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.path=/swagger-ui