version: '3.8'

services:
  postgis:
    image: postgis/postgis:16-3.4
    container_name: postgis_container
    restart: always
    environment:
      POSTGRES_DB: reco_df_db
      POSTGRES_USER: reco_df
      POSTGRES_PASSWORD: reco_df_pass
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

volumes:
  postgis_data:
